CretaceousClient/Models/Animal.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CretaceousClient.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }
    public string Species { get; set; }
    public int Age { get; set; }
    public string Gender { get; set; }

    public static List<Animal> GetAnimals()
    {
      var apiCallTask = ApiHelper.GetAll();
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Animal> animalList = JsonConvert.DeserializeObject<List<Animal>>(jsonResponse.ToString());

      return animalList;
    }
    public static Animal GetDetails(int id)
    {
      var apiCallTask = ApiHelper.Get(id);
      var result = apiCallTask.Result;
      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Animal animal = JsonConvert.DeserializeObject<Animal>(jsonResponse.ToString());

      return animal;
    }

    public static void Post(Animal animal)
    {
      string jsonAnimal = JsonConvert.SerializeObject(animal);
      var apiCallTask = ApiHelper.Post(jsonAnimal);
    }

    public static void Put(Animal animal)
    {
      string jsonAnimal = JsonConvert.SerializeObject(animal);
      var apiCallTask = ApiHelper.Put(animal.AnimalId, jsonAnimal);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.Delete(id);
    }
    
  }
}

CretaceousClient/Models/ApiHelper.cs
using System.Threading.Tasks;
using RestSharp;

namespace CretaceousClient.Models
{
  class ApiHelper
  {
    public static async Task<string> GetAll()
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"animals", Method.GET);
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }

    public static async Task<string> Get(int id)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"animals/{id}", Method.GET);
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }
    public static async Task Post(string newAnimal)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"animals", Method.POST);
      request.AddHeader("Content-Type", "application/json");
      request.AddJsonBody(newAnimal);
      var response = await client.ExecuteTaskAsync(request);
    }

    public static async Task Put(int id, string newAnimal)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"animals/{id}", Method.PUT);
      request.AddHeader("Content-Type", "application/json");
      request.AddJsonBody(newAnimal);
      var response = await client.ExecuteTaskAsync(request);
    }

    public static async Task Delete(int id)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"animals/{id}", Method.DELETE);
      request.AddHeader("Content-Type", "application/json");
      var response = await client.ExecuteTaskAsync(request);
    }
  }
}

CretaceousClient/Models/ErrorViewModel.cs
using System;

namespace CretaceousClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CretaceousClient/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CretaceousClient.Models;

namespace CretaceousClient.Controllers
{
    public class AnimalsController : Controller
    {
      public IActionResult Index()
      {
        var allAnimals = Animal.GetAnimals();
        return View(allAnimals);
      }

      public IActionResult Details(int id)
      {
        var animalDetails = Animal.GetDetails(id);
        return View(animalDetails);
      }
      public IActionResult Delete(int id)
      {
        Animal.Delete(id);
        return RedirectToAction("Index");
      }
      public IActionResult Edit(int id)
      {
        var animal = Animal.GetDetails(id);
        return View(animal);
      }

      [HttpPost]
      public IActionResult Edit(Animal animal)
      {
        Animal.Put(animal);
        return RedirectToAction("Details", new {id = animal.AnimalId});
      }
      public IActionResult Create()
      {
        return View();
      }
      
      [HttpPost]
      public IActionResult Create(Animal animal)
      {
        Animal.Post(animal); 
        return RedirectToAction("Index");
      }

    }
}

CretaceousClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CretaceousClient.Models;

namespace CretaceousClient.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CretaceousClient/Views/Animals/Create.cshtml
@model CretaceousClient.Models.Animal

<h1>Create a New Animal!</h1>

  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Species)
    @Html.TextBoxFor(model => model.Species)

    <br>
    @Html.LabelFor(model => model.Age)
    @Html.TextBoxFor(model => model.Age)

    <br>

    @Html.LabelFor(model => model.Gender)
    @Html.TextBoxFor(model => model.Gender)   

    <br>
    <input type="submit" value="Add An Animal" class="btn btn-dark">
  }
  @Html.ActionLink("Go Home", "Index")

CretaceousClient/Views/Animals/Details.cshtml
<h1>The Animals Details</h1>
<br>
<p>Animal Name: @Model.Name</p>  
<p>Species: @Model.Species</p>
<p>Age: @Model.Age</p>
<p>Gender: @Model.Gender</p>


<a href="/Animals/Delete/@(Model.AnimalId)">Delete this Animal</a>
<br>
<a href="/Animals/Edit/@(Model.AnimalId)">Edit this Animal</a>

CretaceousClient/Views/Animals/Edit.cshtml
@model CretaceousClient.Models.Animal

<h1>Edit this Animals information</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.AnimalId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Gender)
    @Html.EditorFor(model => model.Gender)

    @Html.LabelFor(model => model.Species)
    @Html.EditorFor(model => model.Species)

    @Html.LabelFor(model => model.Age)
    @Html.EditorFor(model => model.Age)

    <br>
    <br>

    <input type="submit" value="Save Details" />
}


@* EPICODUS REMOTE REPO *@
@* <form action="/Animals/Details/@(Model.AnimalId)" method="post">
  <label for="name">Animal's Name</label>
  <input id="name" name="name" type="text" value="@(Model.Name)">
  <label for="species">Animal's Species</label>
  <input id="species" name="species" type="text" value="@(Model.Species)">
  <label for="age">Animal's Age</label>
  <input id="age" name="age" type="number" value="@(Model.Age)">
  <label for="gender">Animal's Gender</label>
  <input id="gender" name="gender" type="text" value="@(Model.Gender)">
  <button type="submit">Go!</button>
</form> *@

  @* [HttpPost]
  public IActionResult Details(int id, Animal animal)
  {
    animal.AnimalId = id;
    Animal.Put(animal);
    return RedirectToAction("Details", id);
  } *@


@* TABLE TEMPLATE *@
  @* @using (Html.BeginForm("Put", "Animals"))
  {
    @Html.HiddenFor(model => model.AnimalId)
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Species</th>
                <th>Age</th>
                <th>Gender</th>
        </tr>
        </thead>
        <tbody>
                <tr>
                    <td>@Model.Name @Html.EditorFor(model => model.Name)</td>
                    <td>@Model.Species</td>
                    <td>@Model.Age</td>
                    <td>@Model.Gender</td>
                </tr>
        </tbody>
    </table>

    <input type="submit" value="Submit Edits" class="btn btn-default" />
  } *@

CretaceousClient/Views/Animals/Index.cshtml
<p>@Html.ActionLink("Create An Animal", "Create", "Animals")</p>
<br> 

<h1>All Animals:</h1>

<ol>
@foreach (Animal animal in Model)
{
    <ul>
        <li>ID: @animal.AnimalId</li>
        <li>Name: @animal.Name</li>
        <li>Species: @animal.Species</li>
        <li>Age: @animal.Age</li>
        <li>Gender: @animal.Gender</li>
    </ul>
    <a href="/Animals/Details/@(animal.AnimalId)"><p>View Details</p></a>

    @* @Html.ActionLink("View Details", "Details", "Animals", new {id = Model[0].AnimalId}) *@

    <br>
}
</ol>

CretaceousClient/Views/Animals/Put.cshtml
@model CretaceousClient.Models.Animal

<h1>Edit this Animals information</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.AnimalId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Gender)
    @Html.EditorFor(model => model.Gender)

    @Html.LabelFor(model => model.Species)
    @Html.EditorFor(model => model.Species)

    @Html.LabelFor(model => model.Age)
    @Html.EditorFor(model => model.Age)

    <br>
    <br>

    <input type="submit" value="Save Details" />
}


@* EPICODUS REMOTE REPO *@
@* <form action="/Animals/Details/@(Model.AnimalId)" method="post">
  <label for="name">Animal's Name</label>
  <input id="name" name="name" type="text" value="@(Model.Name)">
  <label for="species">Animal's Species</label>
  <input id="species" name="species" type="text" value="@(Model.Species)">
  <label for="age">Animal's Age</label>
  <input id="age" name="age" type="number" value="@(Model.Age)">
  <label for="gender">Animal's Gender</label>
  <input id="gender" name="gender" type="text" value="@(Model.Gender)">
  <button type="submit">Go!</button>
</form> *@

  @* [HttpPost]
  public IActionResult Details(int id, Animal animal)
  {
    animal.AnimalId = id;
    Animal.Put(animal);
    return RedirectToAction("Details", id);
  } *@






@* TABLE TEMPLATE *@
  @* @using (Html.BeginForm("Put", "Animals"))
  {
    @Html.HiddenFor(model => model.AnimalId)
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Species</th>
                <th>Age</th>
                <th>Gender</th>
        </tr>
        </thead>
        <tbody>
                <tr>
                    <td>@Model.Name @Html.EditorFor(model => model.Name)</td>
                    <td>@Model.Species</td>
                    <td>@Model.Age</td>
                    <td>@Model.Gender</td>
                </tr>
        </tbody>
    </table>

    <input type="submit" value="Submit Edits" class="btn btn-default" />
  } *@

CretaceousClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>@Html.ActionLink("Animal List", "Index", "Animals")</p>
</div>

CretaceousClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CretaceousClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CretaceousClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CretaceousClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>